from pathlib import Path
import sys
import json

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "evaluation"))

from llm_judge import _parse_score_output, _validate_score


def test_judge_schema_validation_accepts_integer_scores():
    payload = {
        "correctness": 1,
        "groundedness": 2,
        "relevance": 3,
        "helpfulness": 4,
        "tone": 5,
        "overall_score": 3,
        "brief_reason": "Evidence supports part of the response.",
    }
    assert _validate_score(payload) == payload


def test_judge_schema_validation_rejects_probability_like_scores():
    payload = {
        "correctness": 1.5,
        "groundedness": 2,
        "relevance": 3,
        "helpfulness": 4,
        "tone": 5,
        "overall_score": 3,
        "brief_reason": "Invalid score.",
    }
    with pytest.raises(ValueError):
        _validate_score(payload)


def test_judge_schema_validation_normalizes_integral_float():
    payload = {
        "correctness": 1,
        "groundedness": 2,
        "relevance": 3,
        "helpfulness": 4,
        "tone": 5,
        "overall_score": 4.0,
        "brief_reason": "Valid integral score.",
    }
    assert _validate_score(payload)["overall_score"] == 3


def test_judge_schema_validation_accepts_markdown_fence_and_numeric_strings():
    payload = {
        "correctness": "1",
        "groundedness": "4",
        "relevance": "4",
        "helpfulness": "1",
        "tone": "3",
        "overall_score": "3",
        "brief_reason": "Valid string scores.",
    }
    raw = " \n```json\n" + json.dumps(payload) + "\n```\n"
    assert _parse_score_output(raw)["overall_score"] == 3


def test_judge_schema_validation_derives_decimal_overall():
    payload = {
        "correctness": 1,
        "groundedness": 4,
        "relevance": 4,
        "helpfulness": 1,
        "tone": 3,
        "overall_score": 3.6,
        "brief_reason": "Derived overall score.",
    }
    result = _validate_score(payload)
    assert result["overall_score"] == 3


def test_judge_schema_validation_derives_out_of_range_model_overall():
    payload = {
        "correctness": 1,
        "groundedness": 4,
        "relevance": 4,
        "helpfulness": 4,
        "tone": 4,
        "overall_score": 20,
        "brief_reason": "The model supplied an unreliable aggregate.",
    }
    assert _validate_score(payload)["overall_score"] == 3


def test_judge_schema_validation_rejects_invalid_criterion():
    payload = {
        "correctness": 0,
        "groundedness": 4,
        "relevance": 4,
        "helpfulness": 1,
        "tone": 3,
        "overall_score": 3,
        "brief_reason": "Invalid criterion.",
    }
    with pytest.raises(ValueError, match="correctness"):
        _validate_score(payload)


def test_judge_schema_validation_rejects_missing_criterion():
    payload = {
        "correctness": 1,
        "groundedness": 4,
        "relevance": 4,
        "helpfulness": 1,
        "overall_score": 3,
        "brief_reason": "Missing tone.",
    }
    with pytest.raises(ValueError, match="missing"):
        _validate_score(payload)


def test_human_response_template_has_fifty_blank_rows():
    path = ROOT / "evaluation" / "human_response_eval.csv"
    if not path.exists():
        pytest.skip("Template is generated by prepare_response_evaluation.py")
    frame = pd.read_csv(path, dtype=str).fillna("")
    assert len(frame) == 50
    assert frame["example_id"].is_unique
    for column in [
        "correctness_human",
        "groundedness_human",
        "relevance_human",
        "helpfulness_human",
        "tone_human",
        "overall_human",
    ]:
        assert frame[column].eq("").all()
